### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/awf_velodyne#40]
I have removed the previously forked repository.

@miursh and @mitsudome-r if you approve, I'd like to change the repository name to `awf_velodyne` in github.

cc. @esteve

**Comment by mitsudome-r** [comment]
@xmfcx I have renamed the repository and changed the main branch to awf/main.

I have renamed:

- velodyne_driver -> awf_velodyne_driver
- velodyne_pointcloud -> awf_velodyne_pointcloud

I've also added COLCON_IGNORE to velodyne_msgs since the messages seems to be the same with the upstream, and I thought it doesn't worth creating a new message with different namespace.

I didn't rename the packages with COLCON_IGNORE. Maybe we can remove them to make it obvious that we are not using them.

remaining tasks:
- [x] change repos file
- [x] change launch files in autoware_launch

**Comment by esteve** [comment]
@mitsudome-r looks good to me, thanks. If we're ignoring the `velodyne_msgs` package anyway, would it make sense to remove it entirely? Or is the expectation that eventually the `awf_velodyne` packages will be submitted upstream for merging?

**Comment by mitsudome-r** [comment]
@esteve 
I talked with @drwnz about pushing it to upstream.
 We have diverged quite a lot from the upstream, and we don't currently have plans to submit the chnage to upstream.

Instead, TIER IV is planning to migrate to a different LiDAR driver that can handle more LiDAR models.

**Comment by xmfcx** [comment]
Related PRs:
- https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/58
- https://github.com/autowarefoundation/autoware/pull/3492

**Comment by mitsudome-r** [comment]
I removed the packages with COLCON_IGNORE in awf/main branch

**Comment by xmfcx** [comment]
The velodyne driver is no longer used in the Autoware.
We use nebula driver now.
Closing the Issue.
